#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-forked
Version  : 1.4.0
Release  : 29
URL      : https://files.pythonhosted.org/packages/f1/bc/0121a2e386b261b69f4f5aa48e5304c947451dce70d68628cb28d5cd0d28/pytest-forked-1.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f1/bc/0121a2e386b261b69f4f5aa48e5304c947451dce70d68628cb28d5cd0d28/pytest-forked-1.4.0.tar.gz
Summary  : run tests in isolated forked subprocesses
Group    : Development/Tools
License  : MIT
Requires: pytest-forked-license = %{version}-%{release}
Requires: pytest-forked-python = %{version}-%{release}
Requires: pytest-forked-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
====================================================

%package license
Summary: license components for the pytest-forked package.
Group: Default

%description license
license components for the pytest-forked package.


%package python
Summary: python components for the pytest-forked package.
Group: Default
Requires: pytest-forked-python3 = %{version}-%{release}

%description python
python components for the pytest-forked package.


%package python3
Summary: python3 components for the pytest-forked package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_forked)
Requires: pypi(py)
Requires: pypi(pytest)

%description python3
python3 components for the pytest-forked package.


%prep
%setup -q -n pytest-forked-1.4.0
cd %{_builddir}/pytest-forked-1.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639421134
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-forked
cp %{_builddir}/pytest-forked-1.4.0/LICENSE %{buildroot}/usr/share/package-licenses/pytest-forked/82dbfd684f7c04da81d4faa852c6317142daa3e7
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-forked/82dbfd684f7c04da81d4faa852c6317142daa3e7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
